/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul7_1;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ujiKebolehan extends javax.swing.JFrame {

    /**
     * Creates new form ujiKebolehan
     */
    public ujiKebolehan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        knama = new javax.swing.JTextField();
        ktinggi = new javax.swing.JTextField();
        kberat = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        hitung = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        kideal = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Cek ideal tubuh");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 11, 74, 14);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 60, 14);

        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 80, 60, 14);

        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 70, 14);

        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 150, 80, 14);
        getContentPane().add(knama);
        knama.setBounds(140, 40, 140, 30);
        getContentPane().add(ktinggi);
        ktinggi.setBounds(140, 70, 140, 30);
        getContentPane().add(kberat);
        kberat.setBounds(140, 100, 140, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Perempuan");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(140, 140, 100, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Laki-laki");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(240, 140, 100, 23);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(50, 190, 90, 23);

        jButton2.setText("Coba lagi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(147, 190, 90, 23);

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 190, 90, 23);

        jLabel6.setText("Berat badan anda adalah");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 240, 140, 14);

        kideal.setEditable(false);
        kideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kidealActionPerformed(evt);
            }
        });
        getContentPane().add(kideal);
        kideal.setBounds(230, 230, 90, 30);

        hasil.setEditable(false);
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        getContentPane().add(hasil);
        hasil.setBounds(30, 270, 460, 40);

        saran.setEditable(false);
        getContentPane().add(saran);
        saran.setBounds(30, 310, 460, 40);

        jLabel7.setText("cm");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(280, 80, 50, 14);

        jLabel8.setText("kg");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 110, 50, 14);

        setBounds(0, 0, 533, 399);
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        if(knama.getText().equals("")||ktinggi.getText().equals("")
                |kberat.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Data harus diisikan semua");
        }else if(jRadioButton1.isSelected()||jRadioButton2.isSelected()){
            try{
                Proses();
                
            }catch (Exception E){
                JOptionPane.showMessageDialog(null,"Inputan ada yang belum diiisi");
                
            }
        }else{
                    JOptionPane.showMessageDialog(null,"Radio button harus dipilih");
                    }
        // TODO add your handling code here:
    }//GEN-LAST:event_hitungActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void kidealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kidealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kidealActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
knama.setText("");
ktinggi.setText("");
kberat.setText("");
buttonGroup1.clearSelection();
kideal.setText("");
hasil.setText("");
saran.setText("");

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ujiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ujiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ujiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ujiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ujiKebolehan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField kberat;
    private javax.swing.JTextField kideal;
    private javax.swing.JTextField knama;
    private javax.swing.JTextField ktinggi;
    private javax.swing.JTextField saran;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        Double ti = Double.valueOf(ktinggi.getText());
        Double bt = Double.valueOf(kberat.getText());
        Double h1 = null;
        String temp = "";
        
        if (jRadioButton1.isSelected()){
            h1 =(ti - 100) * 1;
            
        }else if (jRadioButton2.isSelected()){
            h1 = (ti - 104) * 1;
        }
        temp = Double.toString(h1.intValue());
        
        if (h1 < bt) {
            kideal.setText(temp);
            hasil.setText("Maaf" + knama.getText() + " , Sepertinya anda overweight :(");
            saran.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
            
        }else if (h1 < bt) {
            kideal.setText(temp);
            hasil.setText("Maaf" +knama.getText() + " , Sepertinya anda underweight");
            saran.setText("Banyaklah mengkonsumsi makanan yang berkabohidrat ");
            
        }else {
            kideal.setText(temp);
            hasil.setText("Maaf" + knama.getText() + " , Berat badan anda sudah ideal");
            saran.setText("Lanjutkan pola makan teratur dan gaya hidup sehat");
        }
        
    }

}
